Mentoring limit ignores private requests
exercism/website pull request #2727
Opened 2022-06-21 09:48 UTC by ErikSchierboom

2022-06-21 09:52 UTC, ErikSchierboom commented on app/controllers/mentoring/external_requests_controller.rb
> +    discussion = Mentor::Request::AcceptExternal.(current_user, @solution)
I've taken the opportunity to move this functionality into its own command. Let me know what you think about the name.

2022-06-21 09:52 UTC, ErikSchierboom commented on app/models/user_track/mentoring_slots.rb
> +    active_mentoring_discussions.size - active_external_mentoring_discussions.size +
This is the core change: ignoring any active, external mentoring discussions

2022-06-21 09:52 UTC, ErikSchierboom commented on db/migrate/20220621081536_add_external_to_mentor_request_and_discussion.rb
> +    add_column :mentor_discussions, :external, :boolean, default: false, null: false, if_not_exists: true
So far, I've chosen to add the `external` property to both the request and discussion, although technically I only need it on discussions for this PR. I'm happy to remove it from requests if you think that would be better.

2022-06-21 09:52 UTC, ErikSchierboom commented on db/migrate/20220621081536_add_external_to_mentor_request_and_discussion.rb
> +    Mentor::Discussion.joins(:request).where('request.external': true).update_all(external: true)
Looking at the existing data, I think the only way to extract whether something was accepted via an external request was to check the fixed comment markdown value. In theory, someone could have used the exact same comment and we'd flag it as private here, but that may not be very likely.

2022-06-23 14:15 UTC, iHiD commented on db/migrate/20220621081536_add_external_to_mentor_request_and_discussion.rb
> +    Mentor::Discussion.joins(:request).where('request.external': true).update_all(external: true)
Don't run these in the migration, run them manually afterwards on bastion. 

If they blow up for any reason (which often happens to me!) then you'll have a migration in a half-run state and it's a real pain to get out of (involves multiple deploys of commenting and uncommenting - or fudging on bastion).

So I'd wrap them in `unless Rails.env.production?` so we still get them locally, but not when we deploy.

2022-06-23 14:16 UTC, iHiD commented on app/models/user_track/mentoring_slots.rb
> +      pending_mentoring_requests.size
```suggestion
    active_mentoring_discussions.where.not(:external).count + pending_mentoring_requests.count
```

2022-06-23 14:16 UTC, iHiD commented on app/models/user_track/mentoring_slots.rb
> +      pending_mentoring_requests.size
Better to just not include the external ones via SQL, I think.

2022-06-23 14:17 UTC, iHiD requested changes
This is great pending my suggestions! :)

2022-06-24 10:59 UTC, iHiD approved these changes
Great! When you run it in production, you'll want to set the isolation level to read_committed to avoid locking. Message me if you're unsure how.

2022-06-27 07:00 UTC, merged

2022-06-27 07:26 UTC, ErikSchierboom commented
@iHiD I've ran the query using `READ_COMMITTED`.